#pragma once
#include "RenderPassesBase.h"
#include "ClearBufferPass.h"
#include "HorizontalBlurPass.h"
#include "LambertianPass.h"
#include "OutlineDrawBlurPass.h"
#include "OutlineDrawPass.h"
#include "OutlineGenerationPass.h"
#include "VerticalBlurPass.h"