#pragma once

#include "RenderPass/DirectionalLight.h"
#include "RenderPass/HDRGammaCorrection.h"
#include "RenderPass/HorizontalBlur.h"
#include "RenderPass/Lambertian.h"
#include "RenderPass/LambertianDepthCopy.h"
#include "RenderPass/LightCombine.h"
#include "RenderPass/OutlineDraw.h"
#include "RenderPass/PointLight.h"
#include "RenderPass/Skybox.h"
#include "RenderPass/SpotLight.h"
#include "RenderPass/SSAO.h"
#include "RenderPass/VerticalBlur.h"
#include "RenderPass/Wireframe.h"